// <auto-generated />
using System;
using DnDApi.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230226192459_ManyToMany")]
    partial class ManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassFeature", b =>
                {
                    b.Property<Guid>("ClassesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FeaturesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClassesId", "FeaturesId");

                    b.HasIndex("FeaturesId");

                    b.ToTable("ClassFeature");
                });

            modelBuilder.Entity("DnDApi.Shared.DTOs.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArmorProficiency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HitDice")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SavingThrows")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolsProficiency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeaponProficiency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("DnDApi.Shared.DTOs.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feature", (string)null);
                });

            modelBuilder.Entity("DnDApi.Shared.DTOs.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlySpeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwimSpeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Race", (string)null);
                });

            modelBuilder.Entity("DnDApi.Shared.DTOs.SubClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("SubClass", (string)null);
                });

            modelBuilder.Entity("DnDApi.Shared.DTOs.SubRace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("SubRace", (string)null);
                });

            modelBuilder.Entity("FeatureRace", b =>
                {
                    b.Property<Guid>("FeaturesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RacesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FeaturesId", "RacesId");

                    b.HasIndex("RacesId");

                    b.ToTable("FeatureRace");
                });

            modelBuilder.Entity("FeatureSubClass", b =>
                {
                    b.Property<Guid>("FeaturesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubClassesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FeaturesId", "SubClassesId");

                    b.HasIndex("SubClassesId");

                    b.ToTable("FeatureSubClass");
                });

            modelBuilder.Entity("FeatureSubRace", b =>
                {
                    b.Property<Guid>("FeaturesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubRacesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FeaturesId", "SubRacesId");

                    b.HasIndex("SubRacesId");

                    b.ToTable("FeatureSubRace");
                });

            modelBuilder.Entity("ClassFeature", b =>
                {
                    b.HasOne("DnDApi.Shared.DTOs.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDApi.Shared.DTOs.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DnDApi.Shared.DTOs.SubClass", b =>
                {
                    b.HasOne("DnDApi.Shared.DTOs.Class", null)
                        .WithMany("SubClasses")
                        .HasForeignKey("ClassId");
                });

            modelBuilder.Entity("DnDApi.Shared.DTOs.SubRace", b =>
                {
                    b.HasOne("DnDApi.Shared.DTOs.Race", null)
                        .WithMany("SubRaces")
                        .HasForeignKey("RaceId");
                });

            modelBuilder.Entity("FeatureRace", b =>
                {
                    b.HasOne("DnDApi.Shared.DTOs.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDApi.Shared.DTOs.Race", null)
                        .WithMany()
                        .HasForeignKey("RacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeatureSubClass", b =>
                {
                    b.HasOne("DnDApi.Shared.DTOs.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDApi.Shared.DTOs.SubClass", null)
                        .WithMany()
                        .HasForeignKey("SubClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeatureSubRace", b =>
                {
                    b.HasOne("DnDApi.Shared.DTOs.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDApi.Shared.DTOs.SubRace", null)
                        .WithMany()
                        .HasForeignKey("SubRacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DnDApi.Shared.DTOs.Class", b =>
                {
                    b.Navigation("SubClasses");
                });

            modelBuilder.Entity("DnDApi.Shared.DTOs.Race", b =>
                {
                    b.Navigation("SubRaces");
                });
#pragma warning restore 612, 618
        }
    }
}
